export const props = {
  name: String,
  type: String,
  label: String,
  value: String,
  placeholder: String,
  disabled: Boolean,
  required: Boolean,
  spellcheck: Boolean,
  help: String,
  minlength: Number,
  maxlength: Number,
  size: String,
  buttons: Array,
  inline: Boolean,
  highlights: Array,
  kirbytags: Array,
  endpoints: Object,
}
