export const props = {
	name: String,
	label: String,
	value: String,
	pretty: Boolean,
	placeholder: String,
	disabled: Boolean,
	required: Boolean,
	spellcheck: Boolean,
	help: String,
	minlength: Number,
	maxlength: Number,
	size: String,
	buttons: Array,
	inline: Boolean,
	highlights: Array,
	customButtons: Object,
	kirbytags: Array,
	links: Object,
	files: Object,
	endpoints: Object,
	uploads: [Object, Boolean],
};
