import type { PropType } from "vue";
import type {
	ButtonItem,
	HighlightPattern,
	CustomButtonConfig,
	LinksConfig,
	FilesConfig,
	EndpointsConfig,
	UploadsConfig,
	UuidConfig,
} from "../types";

export const props = {
	name: String,
	label: String,
	value: String,
	pretty: Boolean,
	placeholder: String,
	disabled: Boolean,
	required: Boolean,
	spellcheck: Boolean,
	help: String,
	minlength: Number,
	maxlength: Number,
	size: String,
	buttons: Array as PropType<ButtonItem[]>,
	inline: Boolean,
	highlights: Array as PropType<HighlightPattern[]>,
	customButtons: Object as PropType<Record<string, CustomButtonConfig>>,
	kirbytags: Array as PropType<string[]>,
	links: Object as PropType<LinksConfig>,
	files: Object as PropType<FilesConfig>,
	endpoints: Object as PropType<EndpointsConfig>,
	uploads: [Object, Boolean] as PropType<UploadsConfig | false>,
	uuid: Object as PropType<UuidConfig>,
};
